
package Server_client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenerickiKontrolerServer", targetNamespace = "http://Server/", wsdlLocation = "http://localhost:8080/SWS/GenerickiKontrolerServer?wsdl")
public class GenerickiKontrolerServer_Service
    extends Service
{

    private final static URL GENERICKIKONTROLERSERVER_WSDL_LOCATION;
    private final static WebServiceException GENERICKIKONTROLERSERVER_EXCEPTION;
    private final static QName GENERICKIKONTROLERSERVER_QNAME = new QName("http://Server/", "GenerickiKontrolerServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SWS/GenerickiKontrolerServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERICKIKONTROLERSERVER_WSDL_LOCATION = url;
        GENERICKIKONTROLERSERVER_EXCEPTION = e;
    }

    public GenerickiKontrolerServer_Service() {
        super(__getWsdlLocation(), GENERICKIKONTROLERSERVER_QNAME);
    }

    public GenerickiKontrolerServer_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERICKIKONTROLERSERVER_QNAME, features);
    }

    public GenerickiKontrolerServer_Service(URL wsdlLocation) {
        super(wsdlLocation, GENERICKIKONTROLERSERVER_QNAME);
    }

    public GenerickiKontrolerServer_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERICKIKONTROLERSERVER_QNAME, features);
    }

    public GenerickiKontrolerServer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenerickiKontrolerServer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenerickiKontrolerServer
     */
    @WebEndpoint(name = "GenerickiKontrolerServerPort")
    public GenerickiKontrolerServer getGenerickiKontrolerServerPort() {
        return super.getPort(new QName("http://Server/", "GenerickiKontrolerServerPort"), GenerickiKontrolerServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenerickiKontrolerServer
     */
    @WebEndpoint(name = "GenerickiKontrolerServerPort")
    public GenerickiKontrolerServer getGenerickiKontrolerServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Server/", "GenerickiKontrolerServerPort"), GenerickiKontrolerServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERICKIKONTROLERSERVER_EXCEPTION!= null) {
            throw GENERICKIKONTROLERSERVER_EXCEPTION;
        }
        return GENERICKIKONTROLERSERVER_WSDL_LOCATION;
    }

}
